const projects=[{title:"Meta Ads Campaign Dashboard",category:"Digital Marketing",technology:"Meta Ads • Campaign Management",description:"Meta advertising campaign dashboard showing spending and opportunity metrics.",image:"images/projects/meta-ads-dashboard.svg",liveDemo:"",github:""},{title:"Meta Ads Results",category:"Digital Marketing",technology:"Meta Ads • Performance Results",description:"Meta advertising results snapshot showing messaging conversations, reach, impressions, cost per conversation, and spend.",image:"images/projects/meta-ads-results.svg",liveDemo:"",github:""},{title:"Amin Tailor Shop App",category:"Android Apps",technology:"Android Studio • Java • SQLite",description:"A tailor business management app for customers, orders, and tailoring records.",image:"images/projects/amin-tailor-showcase.svg",liveDemo:"",github:""}];
const grid=document.getElementById("projectGrid"),filters=document.querySelectorAll(".filter"),modal=document.getElementById("modal");
function renderProjects(filter="All"){grid.innerHTML="";projects.filter(p=>filter==="All"||p.category===filter).forEach(p=>{const el=document.createElement("article");el.className="project-card reveal visible";el.innerHTML=`<div class="project-thumb"><img loading="lazy" src="${p.image}" alt="${p.title} project preview"></div><div class="project-body"><div class="tag">${p.category}</div><h3>${p.title}</h3><p>${p.description}</p><div class="project-tech">${p.technology}</div></div>`;el.addEventListener("click",()=>openModal(p));grid.appendChild(el)})}
function openModal(p){document.getElementById("modalImage").src=p.image;document.getElementById("modalImage").alt=p.title;document.getElementById("modalTitle").textContent=p.title;document.getElementById("modalCategory").textContent=p.category;document.getElementById("modalTech").textContent=p.technology;document.getElementById("modalDesc").textContent=p.description;const live=document.getElementById("modalLive"),gh=document.getElementById("modalGithub");live.style.display=p.liveDemo?"inline-flex":"none";gh.style.display=p.github?"inline-flex":"none";if(p.liveDemo)live.href=p.liveDemo;if(p.github)gh.href=p.github;modal.classList.add("open");modal.setAttribute("aria-hidden","false")}
function closeModal(){modal.classList.remove("open");modal.setAttribute("aria-hidden","true")}
renderProjects();filters.forEach(btn=>btn.addEventListener("click",()=>{filters.forEach(b=>b.classList.remove("active"));btn.classList.add("active");renderProjects(btn.dataset.filter)}));document.querySelector(".modal-close").addEventListener("click",closeModal);modal.addEventListener("click",e=>{if(e.target===modal)closeModal()});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
const menu=document.querySelector(".menu-toggle"),mobile=document.querySelector(".mobile-nav");menu.addEventListener("click",()=>{const open=mobile.classList.toggle("open");menu.setAttribute("aria-expanded",open);mobile.setAttribute("aria-hidden",!open)});mobile.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{mobile.classList.remove("open");menu.setAttribute("aria-expanded","false");mobile.setAttribute("aria-hidden","true")}));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")}),{threshold:.12});document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));
const backTop=document.getElementById("backTop");window.addEventListener("scroll",()=>backTop.classList.toggle("show",window.scrollY>600));backTop.addEventListener("click",()=>window.scrollTo({top:0,behavior:"smooth"}));
document.getElementById("contactForm").addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.currentTarget);const msg=[`Hello Digit Buzzer, I would like to discuss a project.`,`Name: ${f.get("name")}`,`Business: ${f.get("business")||"Not provided"}`,`Email: ${f.get("email")}`,`WhatsApp: ${f.get("whatsapp")||"Not provided"}`,`Service: ${f.get("service")}`,`Project Details: ${f.get("details")}`].join("\n");window.open("https://wa.me/923486588922?text="+encodeURIComponent(msg),"_blank","noopener")});